config/routes.rb
Rails.application.routes.draw do
  resources :bookings, only: [:new, :create, :show]

  root 'flights#index'
end

app/models/airport.rb
class Airport < ActiveRecord::Base
	has_many :departing_flights, class_name: "Flight", foreign_key: "from_airport_id"
	has_many :arriving_flights, class_name: "Flight", foreign_key: "to_airport_id"
end

app/models/booking.rb
class Booking < ActiveRecord::Base
	belongs_to :flight
	has_many :passengers
	accepts_nested_attributes_for :passengers

	validates :flight_id, presence: true
end

app/models/flight.rb
class Flight < ActiveRecord::Base
	belongs_to :to_airport, class_name: "Airport"
	belongs_to :from_airport, class_name: "Airport"
	has_many :bookings
	has_many :passengers, :through => :bookings

	def self.search(params)
		if params[:search] #ensure params are from search
			Flight.where(from_airport_id: params[:depart_code], to_airport_id: params[:arrive_code], 
				start_date: params[:start_date])
		else
			Flight.none
		end
	end
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
	has_many :flights, :through => :bookings
	has_many :bookings

	validates :name, presence: true
	validates :email, presence: true, email_format: {message: "Please enter a valid email address"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	def new
		@flight = Flight.find_by(id: params[:flight_id]) unless params[:flight_id].nil?
		@booking = @flight.bookings.build unless params[:flight_id].nil?
		params[:passengers].to_i.times {@booking.passengers.build} unless params[:flight_id].nil?
		if params[:flight_id].nil?
			flash[:error] = "Please select a flight"
			redirect_to root_path 
		end
	end

	def create
		@booking = Booking.new(booking_params)
		@flight = Flight.find_by(id: params[:flight_id])
		if @booking.save
			flash[:success] = "Booking successfully created"
			@booking.passengers.each do |p|
				PassengerMailer.thanks(p).deliver
			end
			redirect_to booking_path(@booking.id)
		else
			flash[:error] = "Error creating booking, please try again later"
			render 'new'
		end
	end

	def show
		@booking = Booking.find_by(id: params[:id])
		@flight = Flight.find_by(id: @booking.flight_id)
	end

	private

	def booking_params
		params.require(:booking).permit(:flight_id, passengers_attributes:[:name, :email])
	end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
	def index
		@flight_options = Flight.all.map{|f| [f.start_date]}.to_set #map dates to array then to set to make unique values
		@airport_options = Airport.all.map{|a| [a.code, a.id]}
		@passengers = (1..4).map{|p| [p.to_s]}


		if params[:depart_code] == params[:arrive_code] && params[:search]
			flash.now[:error] = "Error, departing and arriving airports are the same"
			render 'index'
		else
			if params[:search]
				@flights = Flight.search(params)
			end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<% provide(:title, "Book Ticket") %>

<h2 class="text-center">Booking Details</h2>

<div class="container-fluid">
	<div class="row">
		<div class="well col-md-4 col-md-offset-4">
			<h3>Flight Details</h3>
			<hr>
			<table>
				<thead>
					<tr>
						<th width="50">Flight</th>
						<th width="50">Date</th>
						<th width="50">Time</th>
						<th width="50">From</th>
						<th width="50">To</th>
						<th width="50">Duration</th>
						<th width="50">Passengers</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><%= @flight.id %></td>
    		      		<td><%= @flight.start_date.strftime("%m/%d/%Y")  %></td>
    		      		<td><%= @flight.start_time.strftime("%I:%M %p") %></td>
    		      		<td><%= @flight.from_airport.code %></td>
    		      		<td><%= @flight.to_airport.code %></td>
    		      		<td><%= distance_of_time_in_words(@flight.duration) %></td>
    		      		<td><%= params[:passengers] %></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

<div class="container-fluid">
	<div class="row">
		<div class="well col-md-4 col-md-offset-4">
			<h3>Passenger Details</h3>
			<hr>
			<%= form_for(@booking) do |f| %>
				<% if @booking.errors.any? %>
		          <div id="error_explanation">
		            <h2>
		              <%= pluralize(@booking.errors.count, "error") %> 
		            </h2>
		 
		            <ul>
		              <% @booking.errors.full_messages.each do |msg| %>
		                <li><%= msg %></li>
		              <% end %>
		            </ul>
		          </div>
		          <hr>
		        <% end %>

				<%= hidden_field_tag(:flight_id, params[:flight_id]) %>
				<%= f.hidden_field :flight_id %>
				<%= hidden_field_tag(:passengers, params[:passengers]) %>
				<%= f.hidden_field :passengers %>
				
				<% passenger_num = 1 %>
				
				<%= f.fields_for :passengers do |passenger_form| %>
					<h4>Passenger #<%= passenger_num %></h4>
					<% passenger_num += 1 %>
					<%= passenger_form.label :name %>
					<%= passenger_form.text_field :name %>
					<%= passenger_form.label :email %>
					<%= passenger_form.text_field :email %>
					<hr>
				<% end %>

				<%= f.submit 'Submit Details', class: "btn btn-success col-md-offset-9" %>
			<% end %>	
		</div>
	</div>
</div>

app/views/bookings/show.html.erb
<% provide(:title, "Confirmation") %>

<div class="text-center">
	<h2>Ticket Conformation</h2>
	<p>Your ticket has now been confirmed</p>
	<p>Your booking id is <%= @booking.id %></p>
</div>

<div class="container-fluid">
	<div class="row">
		<div class="well col-md-4 col-md-offset-4">
			<h3>Flight Details</h3>
			<hr>
			<table>
				<thead>
					<tr>
						<th width="50">Flight</th>
						<th width="50">Date</th>
						<th width="50">Time</th>
						<th width="50">From</th>
						<th width="50">To</th>
						<th width="50">Duration</th>
						<th width="50">Passengers</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><%= @flight.id %></td>
    		      		<td><%= @flight.start_date.strftime("%m/%d/%Y")  %></td>
    		      		<td><%= @flight.start_time.strftime("%I:%M %p") %></td>
    		      		<td><%= @flight.from_airport.code %></td>
    		      		<td><%= @flight.to_airport.code %></td>
    		      		<td><%= distance_of_time_in_words(@flight.duration) %></td>
    		      		<td><%= @booking.passengers.length %></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

<div class="container-fluid">
	<div class="row">
		<div class="well col-md-4 col-md-offset-4">
			<h3>Passenger Details</h3>
			<hr>
			<% passenger_num = 1 %>
			<% @booking.passengers.each do |passenger| %>
				<h4>Passenger #<%= passenger_num %></h4>
				<% passenger_num += 1 %>
				<p>Name: <%= passenger.name %></p>
				<p>Email: <%= passenger.email %></p>
				<hr>
			<% end %>
		</div>
	</div>
</div>

app/views/flights/index.html.erb
<% provide(:title, "Search Flights") %>

<h2 class="text-center">Flight Information</h2>
<p class='text-center'><%= flash[:error]%></p>

<div class="container-fluid">
	<div class="row">
		<div class="well col-md-4 col-md-offset-4">
			<h3>Search for a Flight</h3>
			<hr>
			
			<%= form_tag root_path, method: 'get'  do%>
			<%= hidden_field_tag :search %>
			
			<div class="col-md-6">
				<p>Departing from: <%= select_tag :depart_code, options_for_select(@airport_options) %></p>
				<p>Arriving in: <%= select_tag :arrive_code, options_for_select(@airport_options.reverse) %></p>
			</div>
			<div class="col-md-6">
				<p>Date: <%= select_tag :start_date, options_for_select(@flight_options) %></p>
				<p>Number of Passengers: <%= select_tag :passengers, options_for_select(@passengers) %> </p>	
			</div>
			
			<%= submit_tag "Search", :name => nil, class: "btn col-md-offset-10" %>
			<% end %>
		</div>
	</div>
</div>

<% unless @flights.nil? %>
<div class="container-fluid">
	<div class="row">
		<div class="well col-md-4 col-md-offset-4">
			<h3>Search for times</h3>
			<hr>
			<%= form_tag new_booking_path, method: 'get'  do%>
			<table>
				<% @flights.each do |flight| %> 
     				<thead>
     				<tr>
     					<th width="50">Select</th>
     					<th width="50">Flight</th>
     					<th width="50">Date</th>
     					<th width="50">Time</th>
     					<th width="50">From</th>
     					<th width="50">To</th>
     					<th width="50">Duration</th>
     				</tr>
     				</thead>
     				<tbody>
        				<tr>
          					<td><%= radio_button_tag :flight_id, flight.id %></td>
          					<td><%= flight.id %></td>
          					<td><%= flight.start_date.strftime("%m/%d/%Y")  %></td>
          					<td><%= flight.start_time.strftime("%I:%M %p") %></td>
          					<td><%= flight.from_airport.code %></td>
          					<td><%= flight.to_airport.code %></td>
          					<td><%= distance_of_time_in_words(flight.duration) %></td>
   				     	</tr>      
   				   </tbody>
   				 <% end %>
   			</table>
			<%= hidden_field_tag :passengers, params[:passengers] %>
			<hr>
			<%= submit_tag "Continue", :name => nil, class: "btn btn-success col-md-offset-10" %>
			<% end %>
		</div>
	</div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OdinFlightBooker - <%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "OdinFlightBooker", root_url, :class => "navbar-brand" %>
    </div>
  </div>
</nav>

<%= yield %>

</body>
</html>